server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti-explorer?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  config-location: classpath:mybatis-conf.xml
